package pe.ask.auth.input.api.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

@Schema(description = "Payload for confirming TOTP MFA activation")
public record ConfirmMfaRequest(
        @Schema(description = "6-digit TOTP code generated by authenticator app", example = "654321", pattern = "^\\d{6}$", requiredMode = Schema.RequiredMode.REQUIRED)
        @NotBlank(message = "TOTP code is required")
        @Pattern(regexp = "^\\d{6}$", message = "TOTP code must be 6 digits")
        String totpCode
) {
}
