# ============================================================
# Project
# ============================================================

sonar.projectKey=PF-Auth-Service
sonar.projectName='PF-Auth-Service'
sonar.host.url=http://localhost:9000
sonar.token=sqp_db6a70f4cedf31c73117f632e2ed5b856e8a32e7

sonar.sourceEncoding=UTF-8


# ============================================================
# Gradle
#
# Includes non-JVM files such as:
#
# - application.yml
# - Dockerfile
# - compose.yml
# - *.properties
# - configuration files
#
# Do NOT manually define sonar.sources or sonar.tests when
# sonar.gradle.scanAll=true is enabled.
# ============================================================

sonar.gradle.scanAll=true


# ============================================================
# General exclusions
# ============================================================

sonar.exclusions=\
  **/build/**,\
  **/.gradle/**,\
  **/generated/**,\
  sonar.properties

# ============================================================
# Coverage exclusions
#
# Keep this intentionally small.
# Do not exclude DTOs, adapters, services or business logic
# simply to increase coverage.
# ============================================================

sonar.coverage.exclusions=\
  **/*Application.java,\
  **/generated/**


# ============================================================
# Duplication exclusions
# ============================================================

sonar.cpd.exclusions=\
**/generated/**


# ============================================================
# Quality Gate
#
# Better enabled explicitly in CI.
#
# Uncomment if you also want local sonar executions to wait
# for the Quality Gate result.
# ============================================================

# sonar.qualitygate.wait=true
# sonar.qualitygate.timeout=300